
face_cascade_classifier_config: &face_cascade_classifier_config
  path: "./data/haarcascade_frontalface_default.xml"
  scale_factor: 1.3
  min_neighbors: 5


eyes_cascade_classifier_config: &eyes_cascade_classifier_config
  path: "./data/haarcascade_eye.xml"
  scale_factor: 1.2
  min_neighbors: 5

app_config:
  face_cascade_classifier:
    <<: *face_cascade_classifier_config
  eyes_cascade_classifier:
    <<: *eyes_cascade_classifier_config
